var FC={apiKey:"AIzaSyBsgnrbFI4-F_Vy-cD6EB7LRwdJxuAxzL8",authDomain:"project-3074788574588051418.firebaseapp.com",projectId:"project-3074788574588051418",storageBucket:"project-3074788574588051418.firebasestorage.app",messagingSenderId:"967388882827",appId:"1:967388882827:web:78fc09e700a6c903a5718e"};
var db=null,cls=[],cu=null,cfl='all',uns=null,isDk=true,cfCb=null,dtFlA=false,dtFlFld='created',hideTm=false,srvOff=0,autoInt=null,clkInt=null;
var MA=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
var STL={uploaded:'تم الرفع',pending:'قيد المراجعة',refunded:'تم الاسترداد'};
var STC={uploaded:'sb-u',pending:'sb-p',refunded:'sb-d'};
var STI={uploaded:'fa-solid fa-cloud-arrow-up',pending:'fa-solid fa-clock',refunded:'fa-solid fa-circle-check'};
function togTh(){isDk=!isDk;document.documentElement.className=isDk?'':'lt';document.body.style.background='var(--bg)';document.querySelectorAll('.tb i').forEach(function(i){i.className=isDk?'fa-solid fa-sun':'fa-solid fa-moon'});localStorage.setItem('th',isDk?'d':'l');document.getElementById('exM').classList.remove('on')}
(function(){if(localStorage.getItem('th')==='l'){isDk=false;document.documentElement.className='lt'}})();
function en(n){if(n==null)return'';return String(n).replace(/[٠-٩]/g,function(d){return'٠١٢٣٤٥٦٧٨٩'.indexOf(d)}).replace(/[۰-۹]/g,function(d){return'۰۱۲۳۴۵۶٧۸۹'.indexOf(d)})}
function esc(t){if(!t)return'';var d=document.createElement('div');d.textContent=t;return d.innerHTML}
function escA(s){if(!s)return'';return esc(s).replace(/'/g,'&#39;').replace(/"/g,'&quot;')}
function getSt(c){if(c.status)return c.status;return c.refunded?'refunded':'uploaded'}
function gP(){if(!cu)return{canAdd:true,canDelete:true,canEdit:true};if(cu.role==='admin')return{canAdd:true,canDelete:true,canEdit:true};return cu.permissions||{canAdd:true,canDelete:true,canEdit:true}}
function cRf(p,d,c){if(d<=0||p<=0)return 0;return p-((p/d)*c)}
function fmtDt(ts){if(!ts||!ts.seconds)return'—';var d=new Date(ts.seconds*1000);return d.getDate()+' '+MA[d.getMonth()]+' '+d.getFullYear()}
function fmtDtT(ts){if(!ts||!ts.seconds)return'—';var d=new Date(ts.seconds*1000);return d.getDate()+' '+MA[d.getMonth()]+' '+d.getFullYear()+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function fmtDtS(ts){if(!ts||!ts.seconds)return'—';var d=new Date(ts.seconds*1000);return d.getDate()+' '+MA[d.getMonth()]}
function shTH(){return hideTm&&cu&&cu.role!=='admin'}
function hAE(){['lEr','rEr','fEr'].forEach(function(id){var e=document.getElementById(id);if(e)e.style.display='none'});['lU','lP','rU','rP2','fU','fP'].forEach(function(id){var e=document.getElementById(id);if(e)e.classList.remove('er')})}
function sE(id,m){var e=document.getElementById(id);if(e){e.style.display='flex';if(m)e.querySelector('span').textContent=m}}
function sO(id,m){var e=document.getElementById(id);if(e){e.style.display='block';if(m)e.querySelector('span').textContent=m}}
function hO(id){var e=document.getElementById(id);if(e)e.style.display='none'}
function sCf(m,cb){document.getElementById('cfMsg').textContent=m;document.getElementById('cfM').classList.add('on');cfCb=cb}
function cfOk(){document.getElementById('cfM').classList.remove('on');if(cfCb){var fn=cfCb;cfCb=null;fn()}}
function cfNo(){document.getElementById('cfM').classList.remove('on');cfCb=null}
function toast(m,tp){var b=document.getElementById('tBox'),t=document.createElement('div');var co={s:'rgba(34,197,94,.12)',e:'rgba(220,53,69,.12)',i:'rgba(0,212,170,.12)',w:'rgba(245,158,11,.12)'};
var bs={s:'rgba(34,197,94,.25)',e:'rgba(220,53,69,.25)',i:'rgba(0,212,170,.25)',w:'rgba(245,158,11,.25)'};
var ic={s:'fa-solid fa-circle-check',e:'fa-solid fa-circle-xmark',i:'fa-solid fa-circle-info',w:'fa-solid fa-circle-exclamation'};
var cl={s:'#22c55e',e:'#dc3545',i:'#00d4aa',w:'#f59e0b'};var k=tp||'i';
t.className='tI';t.style.cssText='padding:9px 16px;border-radius:10px;font-size:12px;font-weight:600;display:flex;align-items:center;gap:7px;background:'+co[k]+';border:1px solid '+bs[k]+';color:var(--tx);backdrop-filter:blur(8px);box-shadow:0 4px 20px rgba(0,0,0,.2);min-width:200px;max-width:360px;pointer-events:auto';
t.innerHTML='<i class="'+ic[k]+'" style="color:'+cl[k]+';font-size:14px;flex-shrink:0"></i><span>'+esc(m)+'</span>';b.appendChild(t);
setTimeout(function(){t.className='tO';setTimeout(function(){if(t.parentNode)t.parentNode.removeChild(t)},200)},2800)}
function syncST(){if(!db)return;var t1=Date.now();db.collection('_ts').doc('p').set({t:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}).then(function(){return db.collection('_ts').doc('p').get()}).then(function(s){if(!s.exists)return;var v=s.data().t;srvOff=(v.seconds*1000+(v.nanoseconds||0)/1e6)-((t1+Date.now())/2)}).catch(function(){srvOff=0})}
function gSN(){return new Date(Date.now()+srvOff)}
function sSC(){if(clkInt)clearInterval(clkInt);clkInt=setInterval(function(){var e=document.getElementById('srvDisp');if(!e)return;var n=gSN();e.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0')},1000)}
function initDF(){var ms=document.getElementById('dtM'),ys=document.getElementById('dtMY'),yss=document.getElementById('dtY');for(var i=0;i<12;i++){var o=document.createElement('option');o.value=i;o.textContent=MA[i];ms.appendChild(o)}var cy=new Date().getFullYear();for(var y=cy-2;y<=cy+1;y++){var o1=document.createElement('option');o1.value=y;o1.textContent=y;ys.appendChild(o1);var o2=document.createElement('option');o2.value=y;o2.textContent=y;yss.appendChild(o2)}}
function cDT(){var v=document.getElementById('dtType').value;document.getElementById('dtDateBox').style.display=v==='date'?'block':'none';document.getElementById('dtRangeBox').style.display=v==='range'?'block':'none';document.getElementById('dtRangeBox2').style.display=v==='range'?'block':'none';document.getElementById('dtMonthBox').style.display=v==='month'?'block':'none';document.getElementById('dtYearBox').style.display=v==='year'?'block':'none'}
function aDF(){var tp=document.getElementById('dtType').value,inf='',fldLbl='';
dtFlFld=document.getElementById('dtField').value;
fldLbl=dtFlFld==='refund'?' (تاريخ الاسترداد)':' (تاريخ الإضافة)';
if(tp==='date'){var dv=document.getElementById('dtDate').value;if(!dv){toast('اختر تاريخ','e');return}dtFlA='date:'+dv;var p=dv.split('-');inf='يوم: '+parseInt(p[2])+' '+MA[parseInt(p[1])-1]+' '+p[0]+fldLbl}
else if(tp==='range'){var fr=document.getElementById('dtFrom').value,to=document.getElementById('dtTo').value;if(!fr||!to){toast('اختر التاريخين','e');return}dtFlA='range:'+fr+'|'+to;var a=fr.split('-'),b=to.split('-');inf='من '+parseInt(a[2])+' '+MA[parseInt(a[1])-1]+' إلى '+parseInt(b[2])+' '+MA[parseInt(b[1])-1]+fldLbl}
else if(tp==='month'){var m=parseInt(document.getElementById('dtM').value),y=parseInt(document.getElementById('dtMY').value);dtFlA='month:'+y+'-'+m;inf='شهر: '+MA[m]+' '+y+fldLbl}
else{var yr=parseInt(document.getElementById('dtY').value);dtFlA='year:'+yr;inf='سنة: '+yr+fldLbl}
document.getElementById('dtInfo').innerHTML='<span style="color:var(--dm)"><i class="fa-solid fa-calendar-days text-warm"></i> '+inf+'</span>';document.getElementById('dtInfo').style.display='flex';document.getElementById('dtRstBtn').style.display='inline';cfl='all';document.querySelectorAll('#flS .ft').forEach(function(x){x.classList.remove('on')});rnT()}
function rDF(){dtFlA=false;dtFlFld='created';document.getElementById('dtField').value='created';document.getElementById('dtInfo').style.display='none';document.getElementById('dtRstBtn').style.display='none';cfl='all';document.querySelectorAll('#flS .ft').forEach(function(x){x.classList.remove('on')});document.querySelector('#flS .ft').classList.add('on');rnT()}
function mDF(c){if(!dtFlA)return true;
var ts=dtFlFld==='refund'?c.refundDate:c.createdAt;
if(!ts||!ts.seconds)return false;
var d=new Date(ts.seconds*1000);
if(dtFlA.startsWith('date:')){var p=dtFlA.substring(5).split('-');var f=new Date(parseInt(p[0]),parseInt(p[1])-1,parseInt(p[2]));f.setHours(0,0,0,0);var t=new Date(f);t.setHours(23,59,59,999);return d>=f&&d<=t}
if(dtFlA.startsWith('range:')){var parts=dtFlA.substring(6).split('|');var fp=parts[0].split('-'),tp2=parts[1].split('-');var f2=new Date(parseInt(fp[0]),parseInt(fp[1])-1,parseInt(fp[2]));f2.setHours(0,0,0,0);var t2=new Date(parseInt(tp2[0]),parseInt(tp2[1])-1,parseInt(tp2[2]));t2.setHours(23,59,59,999);return d>=f2&&d<=t2}
if(dtFlA.startsWith('month:')){var mv=dtFlA.substring(7).split('-');return d.getFullYear()===parseInt(mv[0])&&d.getMonth()===parseInt(mv[1])}
if(dtFlA.startsWith('year:'))return d.getFullYear()===parseInt(dtFlA.substring(5));return true}
function swT(t){hAE();hO('fOk');hO('rOk');document.getElementById('tabL').classList.toggle('on',t==='l');document.getElementById('tabR').classList.toggle('on',t==='r');document.getElementById('lF').style.display=t==='l'?'block':'none';document.getElementById('rF').style.display=t==='r'?'block':'none';if(t==='l')hideFg()}
function showFg(){document.getElementById('lNorm').style.display='none';document.getElementById('lFg').style.display='block';hO('fOk');hAE()}
function hideFg(){document.getElementById('lNorm').style.display='block';document.getElementById('lFg').style.display='none'}
function doL(){hAE();var u=document.getElementById('lU').value.trim(),p=document.getElementById('lP').value;if(!u){document.getElementById('lU').classList.add('er');sE('lEr','أدخل اسم المستخدم');return}if(!p){document.getElementById('lP').classList.add('er');sE('lEr','أدخل كلمة المرور');return}
var btn=document.getElementById('lBt');btn.disabled=true;btn.innerHTML='<span style="display:inline-block;width:14px;height:14px;border:2px solid transparent;border-top-color:#0b1120;border-radius:50%;animation:spin .6s linear infinite"></span>';
db.collection('users').where('username','==',u).limit(1).get().then(function(s){if(s.empty){sE('lEr','اسم المستخدم غير موجود')}else{var d=s.docs[0].data();if(d.password!==p){sE('lEr','كلمة المرور خاطئة')}else if(d.approved===false){sE('lEr','حسابك بانتظار موافقة الإدارة')}else{cu={id:s.docs[0].id,username:d.username,role:d.role,permissions:d.permissions||{canAdd:true,canDelete:true,canEdit:true}};sessionStorage.setItem('cu',JSON.stringify(cu));shApp();stL();chkP();toast('مرحباً '+cu.username,'s')}}}).catch(function(e){if(e.code==='permission-denied')sE('lEr','خطأ في الصلاحيات');else sE('lEr','خطأ في الاتصال')}).finally(function(){btn.disabled=false;btn.innerHTML='<i class="fa-solid fa-right-to-bracket text-sm"></i> دخول'})}
function doR(){hAE();hO('rOk');var u=document.getElementById('rU').value.trim(),p=document.getElementById('rP').value,p2=document.getElementById('rP2').value;if(!u){document.getElementById('rU').classList.add('er');sE('rEr','أدخل اسم المستخدم');return}if(!p||p.length<3){document.getElementById('rP').classList.add('er');sE('rEr','كلمة المرور قصيرة');return}if(p!==p2){document.getElementById('rP2').classList.add('er');sE('rEr','كلمة المرور غير متطابقة');return}
db.collection('users').where('username','==',u).limit(1).get().then(function(ex){if(!ex.empty){sE('rEr','اسم المستخدم موجود بالفعل');return null}return db.collection('users').get()}).then(function(all){if(!all)return null;var f=all.empty;return db.collection('users').add({username:u,password:p,role:f?'admin':'user',approved:f,permissions:{canAdd:true,canDelete:true,canEdit:true},createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(r){return{id:r.id,rl:f?'admin':'user',ap:f}})}).then(function(res){if(!res)return;if(res.ap){cu={id:res.id,username:u,role:res.rl,permissions:{canAdd:true,canDelete:true,canEdit:true}};sessionStorage.setItem('cu',JSON.stringify(cu));shApp();stL();chkP();toast('تم إنشاء حساب المدير','s')}else{document.getElementById('rU').value='';document.getElementById('rP').value='';document.getElementById('rP2').value='';sO('rOk','تم تسجيل طلبك — بانتظار موافقة الإدارة');toast('تم تسجيل الطلب','s')}}).catch(function(e){if(e.code==='permission-denied')sE('rEr','خطأ في الصلاحيات');else sE('rEr','خطأ: '+e.message)})}
function doFg(){hAE();hO('fOk');var u=document.getElementById('fU').value.trim(),p=document.getElementById('fP').value.trim();if(!u){document.getElementById('fU').classList.add('er');sE('fEr','أدخل اسم المستخدم');return}if(!p||p.length<3){document.getElementById('fP').classList.add('er');sE('fEr','كلمة المرور قصيرة');return}
db.collection('users').where('username','==',u).limit(1).get().then(function(s){if(s.empty){document.getElementById('fU').classList.add('er');sE('fEr','اسم المستخدم غير موجود');return Promise.reject('nf')}return db.collection('passwordResetRequests').where('username','==',u).where('status','==','pending').limit(1).get()}).then(function(ex){if(!ex.empty){sE('fEr','يوجد طلب معلق بالفعل');return}return db.collection('passwordResetRequests').add({username:u,newPassword:p,status:'pending',requestedAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){sO('fOk','تم رفع طلب تغيير كلمة المرور');document.getElementById('fP').value='';document.getElementById('fU').value='';toast('تم رفع الطلب','s')})}).catch(function(e){if(e!=='nf'){if(e.code==='permission-denied')sE('fEr','خطأ في الصلاحيات');else sE('fEr','خطأ: '+e.message)}})}
function doOut(){if(uns)uns();if(autoInt){clearInterval(autoInt);autoInt=null}if(clkInt){clearInterval(clkInt);clkInt=null}cu=null;cls=[];hideTm=false;sessionStorage.removeItem('cu');document.getElementById('app').style.display='none';document.getElementById('authScr').style.display='flex';document.getElementById('lU').value='';document.getElementById('lP').value='';hAE()}
function shApp(){document.getElementById('authScr').style.display='none';document.getElementById('app').style.display='block';document.getElementById('uNm').textContent=cu.username;var a=cu.role==='admin';var b=document.getElementById('uBg');b.textContent=a?'مدير':'مستخدم';b.className=a?'rb rb-a':'rb-u';document.getElementById('adB').style.display=a?'inline-flex':'none';document.getElementById('exA').style.display=a?'flex':'none';var exSEl=document.getElementById('exS');if(exSEl)exSEl.style.display=a?'block':'none';var dtFlEl=document.getElementById('dtFl');if(dtFlEl)dtFlEl.style.display=a?'block':'none';document.getElementById('srvClk').style.display=a?'flex':'none';document.getElementById('addBtn').style.display=gP().canAdd?'inline-flex':'none';
db.collection('settings').doc('appSettings').onSnapshot(function(d){if(d.exists)hideTm=d.data().hideTimeInLogs||false;else hideTm=false;rnT()},function(){});
if(a){syncST();sSC();stAT()}}
function stAT(){if(autoInt)clearInterval(autoInt);autoInt=setInterval(chkAT,30000);setTimeout(chkAT,5000)}
function stL(){uns=db.collection('cancellations').orderBy('createdAt','desc').onSnapshot(function(s){cls=s.docs.map(function(d){return{id:d.id,...d.data()}});rnT();upSt()},function(e){toast(e.code==='permission-denied'?'خطأ في الصلاحيات':'خطأ اتصال','e')})}
function chkP(){if(!cu||cu.role!=='admin')return;db.collection('users').where('approved','==',false).get().then(function(s){var t=s.size;return db.collection('passwordResetRequests').where('status','==','pending').get().then(function(p){t+=p.size;t+=cls.filter(function(c){return getSt(c)==='uploaded'}).length;var bg=document.getElementById('pendBdg');if(bg){bg.textContent=t;bg.style.display=t>0?'flex':'none'}})}).catch(function(){})}
function chkAT(){if(!cu||cu.role!=='admin'||!db)return;db.collection('settings').doc('appSettings').get().then(function(doc){if(!doc.exists)return;var s=doc.data();if(!s.autoTransitionEnabled||!s.autoTransitionTime)return;var n=gSN(),pt=s.autoTransitionTime.split(':'),th=parseInt(pt[0]),tm=parseInt(pt[1]);if(isNaN(th)||isNaN(tm))return;if(n.getHours()*60+n.getMinutes()<th*60+tm)return;if(s.lastAutoTransition&&s.lastAutoTransition.seconds){var ld=new Date(s.lastAutoTransition.seconds*1000);if(ld.getFullYear()===n.getFullYear()&&ld.getMonth()===n.getMonth()&&ld.getDate()===n.getDate())return}return db.collection('cancellations').where('status','==','uploaded').get()}).then(function(snap){if(!snap||snap.empty)return;var b=db.batch();snap.docs.forEach(function(d){b.update(d.ref,{status:'pending',refunded:false})});return b.commit().then(function(){return snap.size})}).then(function(cnt){if(cnt&&cnt>0){toast('تحويل تلقائي: '+cnt+' طلب','s');return db.collection('settings').doc('appSettings').update({lastAutoTransition:firebase.firestore.FieldValue.serverTimestamp()})}}).catch(function(e){console.error('[AT]',e)})}
function dMT(){if(!cu||cu.role!=='admin'){toast('للمدير فقط','e');return}toast('جاري التحويل...','i');db.collection('cancellations').where('status','==','uploaded').get().then(function(snap){if(snap.empty){toast('لا توجد طلبات "تم الرفع"','w');return}var b=db.batch();snap.docs.forEach(function(d){b.update(d.ref,{status:'pending',refunded:false})});return b.commit().then(function(){return db.collection('settings').doc('appSettings').update({lastAutoTransition:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){return snap.size})})}).then(function(cnt){if(cnt){toast('تم تحويل '+cnt+' طلب','s');ldPd();chkP()}}).catch(function(e){console.error(e);toast('خطأ','e')})}
function tgAT(v){db.collection('settings').doc('appSettings').set({autoTransitionEnabled:v},{merge:true}).then(function(){if(v)stAT();toast(v?'تم تفعيل التحويل التلقائي':'تم تعطيله','s');ldSt()}).catch(function(){toast('خطأ','e')})}
// ✅ FIX: reset lastAutoTransition when time changes so it can re-fire today
function uATT(v){if(!v||!v.match(/^\d{2}:\d{2}$/)){toast('صيغة خاطئة','e');return}db.collection('settings').doc('appSettings').set({autoTransitionTime:v},{merge:true}).then(function(){return db.collection('settings').doc('appSettings').update({lastAutoTransition:firebase.firestore.FieldValue.delete()})}).then(function(){toast('تم تحديد الوقت: '+v,'s');ldSt();setTimeout(chkAT,800)}).catch(function(){toast('خطأ','e')})}
function ldSt(){db.collection('settings').doc('appSettings').get().then(function(doc){var s=doc.exists?doc.data():{};var ae=s.autoTransitionEnabled||false,at=s.autoTransitionTime||'18:00',la=s.lastAutoTransition?fmtDtT(s.lastAutoTransition):'—';var sv=document.getElementById('srvDisp')?document.getElementById('srvDisp').textContent:'—';
document.getElementById('adS').innerHTML='<div class="rounded-lg p-4 mb-3" style="background:var(--cs);border:1px solid var(--brd)"><div class="flex items-center justify-between gap-4"><div class="flex-1"><div class="flex items-center gap-2 mb-1.5"><div class="w-8 h-8 rounded-lg flex items-center justify-center" style="background:rgba(0,212,170,.1)"><i class="fa-solid fa-eye-slash text-accent text-xs"></i></div><h3 class="font-bold text-sm">إخفاء الوقت من السجلات</h3></div><p class="text-[11px] mr-10" style="color:var(--dm)">يتم إخفاء الوقت فقط من تاريخ الاسترداد أمام المستخدمين</p><div class="mt-2 p-2 rounded-lg text-[10px] flex items-center gap-1.5" style="background:rgba(0,212,170,.05);border:1px solid rgba(0,212,170,.1);color:#00d4aa" id="htInfo"><i class="fa-solid fa-shield-halved"></i> الحالة: <strong>'+(hideTm?'مفعّل':'معطّل')+'</strong></div></div><label class="tgg"><input type="checkbox" '+(hideTm?'checked':'')+' onchange="tgHT(this.checked)"><span class="tgg-sl"></span></label></div></div><div class="rounded-lg p-4" style="background:var(--cs);border:1px solid var(--brd)"><div class="flex items-center gap-3 mb-3"><label class="tgg"><input type="checkbox" '+(ae?'checked':'')+' onchange="tgAT(this.checked)"><span class="tgg-sl"></span></label><span class="text-xs font-bold" style="color:var(--dm)">تحويل تلقائي "تم الرفع" ← "قيد المراجعة"</span></div><div class="flex items-center gap-3 flex-wrap"><div><label class="text-[10px] font-bold" style="color:var(--dm)">وقت التحويل اليومي</label><input type="time" class="fi fi-sm" style="width:120px" value="'+at+'" onchange="uATT(this.value)"></div><button type="button" onclick="dMT()" class="bp bp-warm bp-sm px-4 py-1.5"><i class="fa-solid fa-bolt ml-1"></i>تحويل يدوي الآن</button><div class="mr-auto text-[10px]" style="color:var(--mt)"><div><i class="fa-solid fa-server ml-1"></i>السيرفر: <span class="cv font-bold" style="color:var(--dm)">'+sv+'</span></div><div><i class="fa-solid fa-clock-rotate-left ml-1"></i>آخر تحويل: <span class="font-bold" style="color:var(--dm)">'+la+'</span></div></div></div></div>'}).catch(function(){})}
function tgHT(v){hideTm=v;db.collection('settings').doc('appSettings').set({hideTimeInLogs:v},{merge:true}).catch(function(){toast('خطأ','e')});rnT();var i=document.getElementById('htInfo');if(i)i.innerHTML='<i class="fa-solid fa-shield-halved"></i> الحالة: <strong>'+(v?'مفعّل':'معطّل')+'</strong>';toast(v?'تم تفعيل إخفاء الوقت':'تم تعطيله','s')}
function ldPd(){var up=cls.filter(function(c){return getSt(c)==='uploaded'}),pn=cls.filter(function(c){return getSt(c)==='pending'}),tot=up.length+pn.length;document.getElementById('pCt').textContent='('+tot+')';var el=document.getElementById('adP');
if(!tot){el.innerHTML='<div class="text-center py-8" style="color:var(--mt)"><i class="fa-solid fa-circle-check text-2xl mb-2 block text-success"></i><p class="font-bold text-sm">لا توجد طلبات معلقة</p></div>';return}
var h='';if(up.length){h+='<div class="text-xs font-bold mb-2" style="color:var(--dm)"><i class="fa-solid fa-cloud-arrow-up" style="color:#94a3b8"></i> تم الرفع ('+up.length+')</div>';up.forEach(function(c){h+='<div class="rounded-lg p-3 mb-2" style="background:var(--cs);border:1px solid var(--brd);border-right:3px solid #94a3b8"><div class="flex items-start justify-between gap-3"><div class="flex-1"><div class="flex items-center gap-1.5 mb-1"><span class="font-bold text-sm">'+esc(c.name)+'</span>'+(c.previouslyRefunded?'<span class="pb-t"><i class="fa-solid fa-triangle-exclamation"></i> سبق</span>':'')+'</div><div class="text-[11px]" style="color:var(--dm)"><div class="num"><i class="fa-solid fa-phone ml-1" style="color:var(--mt)"></i>'+esc(c.phone||c.mobile||'—')+'</div><div><i class="fa-solid fa-utensils ml-1" style="color:var(--mt)"></i>'+esc(c.packageType)+'</div></div></div><div class="text-left shrink-0"><div class="text-[10px] mb-1.5" style="color:var(--dm)">المبلغ: <span class="text-accent font-bold num">'+en((c.refundAmount||0).toFixed(2))+'</span></div><button type="button" onclick="toPn(\''+c.id+'\')" class="bp bp-warm bp-sm px-3"><i class="fa-solid fa-arrow-left ml-1"></i>تحويل</button></div></div></div>'})}
if(pn.length){h+='<div class="text-xs font-bold mb-2 mt-4" style="color:var(--dm)"><i class="fa-solid fa-clock text-warm"></i> قيد المراجعة ('+pn.length+')</div>';pn.forEach(function(c){h+='<div class="rounded-lg p-3 mb-2" style="background:var(--cs);border:1px solid var(--brd);border-right:3px solid #e97a2a"><div class="flex items-start justify-between gap-3"><div class="flex-1"><div class="flex items-center gap-1.5 mb-1"><span class="font-bold text-sm">'+esc(c.name)+'</span>'+(c.previouslyRefunded?'<span class="pb-t"><i class="fa-solid fa-triangle-exclamation"></i> سبق</span>':'')+'</div><div class="text-[11px]" style="color:var(--dm)"><div class="num"><i class="fa-solid fa-phone ml-1" style="color:var(--mt)"></i>'+esc(c.phone||c.mobile||'—')+'</div><div><i class="fa-solid fa-utensils ml-1" style="color:var(--mt)"></i>'+esc(c.packageType)+'</div></div></div><div class="text-left shrink-0"><div class="text-[10px] mb-1.5" style="color:var(--dm)">المبلغ: <span class="text-accent font-bold num">'+en((c.refundAmount||0).toFixed(2))+'</span></div><button type="button" onclick="apR(\''+c.id+'\')" class="bp bp-sm px-3"><i class="fa-solid fa-check ml-1"></i>موافقة</button></div></div></div>'})}
el.innerHTML=h}
function ldAp(){db.collection('users').where('approved','==',false).get().then(function(s){var n=s.size,bg=document.getElementById('apCt');if(bg){bg.textContent='('+n+')';bg.style.display=n>0?'inline':'none'}var el=document.getElementById('adA');if(!n){el.innerHTML='<div class="text-center py-8" style="color:var(--mt)"><i class="fa-solid fa-user-check text-2xl mb-2 block text-success"></i><p class="font-bold text-sm">لا توجد حسابات معلقة</p></div>';return}
el.innerHTML=s.docs.map(function(d){var u=d.data();return'<div class="rounded-lg p-3 mb-2.5 flex items-center justify-between gap-3" style="background:var(--cs);border:1px solid var(--brd)"><div class="flex items-center gap-2.5"><div class="w-9 h-9 rounded-full flex items-center justify-center font-bold text-sm" style="background:rgba(233,122,42,.1);color:#e97a2a">'+u.username.charAt(0).toUpperCase()+'</div><div><div class="font-bold text-sm">'+esc(u.username)+'</div><div class="text-[10px] mt-0.5" style="color:var(--mt)">'+fmtDt(u.createdAt)+'</div></div></div><div class="flex items-center gap-1.5"><button type="button" onclick="apU(\''+d.id+'\')" class="bp bp-sm px-3"><i class="fa-solid fa-check ml-1"></i>قبول</button><button type="button" onclick="rjU(\''+d.id+'\',\''+escA(u.username)+'\')" class="bd py-1.5 px-2.5"><i class="fa-solid fa-xmark ml-1"></i>رفض</button></div></div>'}).join('')}).catch(function(){toast('خطأ','e')})}
function ldPR(){var el=document.getElementById('adK');el.innerHTML='<div class="text-center py-6"><span style="display:inline-block;width:18px;height:18px;border:2px solid var(--brd);border-top-color:#00d4aa;border-radius:50%;animation:spin .6s linear infinite"></span></div>';
db.collection('passwordResetRequests').where('status','==','pending').get().then(function(s){var docs=s.docs.sort(function(a,b){return(b.data().requestedAt?b.data().requestedAt.seconds:0)-(a.data().requestedAt?a.data().requestedAt.seconds:0)});var n=docs.length,bg=document.getElementById('pwCt');if(bg){bg.textContent='('+n+')';bg.style.display=n>0?'inline':'none'}
if(!n){el.innerHTML='<div class="text-center py-8" style="color:var(--mt)"><i class="fa-solid fa-key text-2xl mb-2 block text-success"></i><p class="font-bold text-sm">لا توجد طلبات</p></div>';return}
el.innerHTML=docs.map(function(d){var r=d.data(),ms='';for(var i=0;i<r.newPassword.length;i++)ms+='●';return'<div class="rounded-xl p-4 mb-3" style="background:var(--cs);border:1px solid var(--brd);border-right:4px solid #f59e0b"><div class="flex items-center justify-between gap-4 flex-wrap"><div class="flex items-center gap-3"><div class="w-11 h-11 rounded-xl flex items-center justify-center" style="background:rgba(245,158,11,.1);color:#f59e0b"><i class="fa-solid fa-key text-sm"></i></div><div><div class="font-bold text-sm mb-1">'+esc(r.username)+'</div><div class="text-[10px]" style="color:var(--mt)">'+fmtDtT(r.requestedAt)+'</div></div></div><div class="flex items-center gap-2"><button type="button" onclick="apPR(\''+d.id+'\',\''+escA(r.username)+'\',\''+escA(r.newPassword)+'\')" class="bp bp-sm px-4 py-1.5"><i class="fa-solid fa-check ml-1"></i>موافقة</button><button type="button" onclick="rjPR(\''+d.id+'\')" class="bd py-1.5 px-3 text-xs"><i class="fa-solid fa-xmark ml-1"></i>رفض</button></div></div><div class="mt-3 pt-3 flex items-center gap-2" style="border-top:1px solid var(--brd)"><span class="text-[11px] font-bold" style="color:var(--dm)"><i class="fa-solid fa-lock ml-1"></i>كلمة المرور:</span><span class="lk-cell px-2.5 py-1 rounded-lg" onclick="tPV(this,\''+escA(r.newPassword)+'\')" style="background:rgba(245,158,11,.08);border:1px solid rgba(245,158,11,.15);color:#f59e0b;font-weight:800;letter-spacing:2px;font-size:13px;cursor:pointer;min-width:80px;text-align:center;display:inline-block" data-m="'+ms+'" data-s="0">'+ms+'</span><span class="text-[9px]" style="color:var(--mt)">(اضغط لعرض)</span></div></div>'}).join('')}).catch(function(){el.innerHTML='<div class="text-center py-8" style="color:#dc3545"><p class="font-bold text-sm">خطأ في التحميل</p></div>'})}
function tPV(el,pw){if(el.dataset.s==='1'){el.textContent=el.dataset.m;el.dataset.s='0';el.style.letterSpacing='2px'}else{el.textContent=pw;el.dataset.s='1';el.style.letterSpacing='0'}}
function apPR(id,un,np){db.collection('users').where('username','==',un).limit(1).get().then(function(s){if(s.empty){toast('غير موجود','e');return}return db.collection('users').doc(s.docs[0].id).update({password:np})}).then(function(){return db.collection('passwordResetRequests').doc(id).update({status:'approved',handledAt:firebase.firestore.FieldValue.serverTimestamp()})}).then(function(){toast('تم تغيير كلمة المرور','s');ldPR();chkP()}).catch(function(){toast('خطأ','e')})}
function rjPR(id){sCf('هل تريد رفض الطلب؟',function(){db.collection('passwordResetRequests').doc(id).update({status:'rejected',handledAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){toast('تم رفض الطلب','i');ldPR();chkP()}).catch(function(){toast('خطأ','e')})})}
function apU(id){db.collection('users').doc(id).update({approved:true}).then(function(){toast('تم قبول الحساب','s');ldAp();ldUr();chkP()}).catch(function(){toast('خطأ','e')})}
function rjU(id,un){sCf('حذف حساب "'+un.replace(/&#39;/g,"'")+'"؟',function(){db.collection('users').doc(id).delete().then(function(){toast('تم رفض الحساب','i');ldAp();ldUr();chkP()}).catch(function(){toast('خطأ','e')})})}
function ldUr(){db.collection('users').orderBy('createdAt','asc').get().then(function(s){var el=document.getElementById('adU'),docs=s.docs.filter(function(d){return d.data().approved!==false});if(!docs.length){el.innerHTML='<div class="text-center py-8" style="color:var(--mt)">لا يوجد مستخدمين</div>';return}
el.innerHTML=docs.map(function(d){var u=d.data(),me=cu&&d.id===cu.id,pm=u.permissions||{canAdd:true,canDelete:true,canEdit:true},ad=u.role==='admin';var ph='';if(!ad){ph='<div class="pm-box"><div class="pm-title"><i class="fa-solid fa-sliders"></i> الصلاحيات</div><div class="pm-row"><span>إضافة</span><label class="tgg"><input type="checkbox" '+(pm.canAdd?'checked':'')+' onchange="tgPm(\''+d.id+'\',\'canAdd\',this.checked)"><span class="tgg-sl"></span></label></div><div class="pm-row"><span>حذف</span><label class="tgg"><input type="checkbox" '+(pm.canDelete?'checked':'')+' onchange="tgPm(\''+d.id+'\',\'canDelete\',this.checked)"><span class="tgg-sl"></span></label></div><div class="pm-row"><span>تعديل</span><label class="tgg"><input type="checkbox" '+(pm.canEdit?'checked':'')+' onchange="tgPm(\''+d.id+'\',\'canEdit\',this.checked)"><span class="tgg-sl"></span></label></div></div>'}
var pw='';if(!me)pw='<div class="flex items-center gap-2 mt-3"><input type="text" id="ri_'+d.id+'" class="fi fi-sm" style="flex:1" placeholder="كلمة مرور جديدة"><button type="button" onclick="cnRP(\''+d.id+'\')" class="bp bp-sm px-3"><i class="fa-solid fa-key ml-1"></i>تغيير</button></div>';
var dl='';if(!me)dl='<button type="button" onclick="dlU(\''+d.id+'\',\''+escA(u.username)+'\')" class="bd mt-3 w-full py-1.5 justify-center"><i class="fa-solid fa-trash-can ml-1"></i> حذف المستخدم</button>';
return'<div class="rounded-lg p-4 mb-3" style="background:var(--cs);border:1px solid var(--brd)"><div class="flex items-center gap-3 mb-1"><div class="w-10 h-10 rounded-full flex items-center justify-center font-bold text-base" style="background:'+(ad?'rgba(0,212,170,.1);color:#00d4aa':'rgba(100,116,139,.1);color:var(--mt)')+'">'+u.username.charAt(0).toUpperCase()+'</div><div class="flex-1"><div class="flex items-center gap-2"><span class="font-bold text-sm">'+esc(u.username)+'</span>'+(me?'<span class="text-[9px] font-bold px-2 py-0.5 rounded-full" style="background:rgba(0,212,170,.1);color:#00d4aa">أنت</span>':'')+'</div><div class="text-[10px]" style="color:var(--mt)">'+(ad?'مدير':'مستخدم')+' — '+fmtDt(u.createdAt)+'</div></div></div>'+ph+pw+dl+'</div>'}).join('')}).catch(function(){toast('خطأ','e')})}
function tgPm(id,p,v){db.collection('users').doc(id).get().then(function(doc){if(!doc.exists)return;var c=doc.data().permissions||{canAdd:true,canDelete:true,canEdit:true};c[p]=v;return db.collection('users').doc(id).update({permissions:c})}).then(function(){toast('تم التحديث','s')}).catch(function(){toast('خطأ','e')})}
function cnRP(id){var np=document.getElementById('ri_'+id).value.trim();if(!np||np.length<3){toast('قصيرة','e');return}db.collection('users').doc(id).update({password:np}).then(function(){toast('تم التغيير','s');ldUr()}).catch(function(){toast('خطأ','e')})}
function dlU(id,un){sCf('حذف المستخدم "'+un.replace(/&#39;/g,"'")+'"؟',function(){db.collection('users').doc(id).delete().then(function(){toast('تم الحذف','i');ldUr();chkP()}).catch(function(){toast('خطأ','e')})})}
function swAT(t,btn){['adP','adA','adK','adU','adS'].forEach(function(i){document.getElementById(i).style.display='none'});['abP','abA','abK','abU','abS'].forEach(function(i){document.getElementById(i).classList.remove('on')});btn.classList.add('on');document.getElementById({p:'adP',a:'adA',k:'adK',u:'adU',s:'adS'}[t]).style.display='block';if(t==='p')ldPd();if(t==='a')ldAp();if(t==='k')ldPR();if(t==='u')ldUr();if(t==='s')ldSt()}
function openAP(){document.getElementById('adM').classList.add('on');ldPd();chkP()}
function clAP(){document.getElementById('adM').classList.remove('on')}
function openCM(){document.getElementById('cmM').classList.add('on');['tmI','fN','fPh','fSub','fPk','fDt','fDr','fPr','fDy','fCo','fRs','fNo'].forEach(function(i){document.getElementById(i).value=''});document.getElementById('pRf').textContent='0.00';document.getElementById('pW').classList.remove('on')}
function clCM(){document.getElementById('cmM').classList.remove('on')}
function sFt(f,btn){cfl=f;document.querySelectorAll('#flS .ft').forEach(function(x){x.classList.remove('on')});btn.classList.add('on');rnT()}
function upSt(){var t=cls.length,tr=cls.reduce(function(s,c){return s+(c.refundAmount||0)},0),rf=cls.filter(function(c){return getSt(c)==='refunded'}),ra=rf.reduce(function(s,c){return s+(c.refundAmount||0)},0),pn=cls.filter(function(c){return getSt(c)==='pending'}),pa=pn.reduce(function(s,c){return s+(c.refundAmount||0)},0),up=cls.filter(function(c){return getSt(c)==='uploaded'});
document.getElementById('sT').textContent=en(t);document.getElementById('sU').textContent=en(up.length);document.getElementById('sTR').textContent=en(tr.toFixed(2));document.getElementById('sR').textContent=en(rf.length);document.getElementById('sRA').textContent=en(ra.toFixed(2))+' ريال';document.getElementById('sP').textContent=en(pn.length);document.getElementById('sPA').textContent=en(pa.toFixed(2))+' ريال'}
function rnT(){var tb=document.getElementById('tB'),sr=document.getElementById('sI').value.trim().toLowerCase(),a=cu&&cu.role==='admin',pm=gP(),ht=shTH();
var fl=cls.filter(function(c){if(!mDF(c))return false;if(sr&&!c.name.toLowerCase().includes(sr)&&!(c.phone||'').toLowerCase().includes(sr)&&!(c.mobile||'').toLowerCase().includes(sr))return false;if(cfl==='uploaded'&&getSt(c)!=='uploaded')return false;if(cfl==='pending'&&getSt(c)!=='pending')return false;if(cfl==='refunded'&&getSt(c)!=='refunded')return false;if(cfl==='prev'&&!c.previouslyRefunded)return false;return true});
var hd=cls.length>0;document.getElementById('empS').style.display=hd?'none':'block';document.getElementById('tbS').style.display=hd?'block':'none';document.getElementById('sS').style.display=hd?'grid':'none';document.getElementById('flS').style.display=hd?'flex':'none';document.getElementById('exB').style.display=hd?'inline-flex':'none';
if(!fl.length){tb.innerHTML='<tr><td colspan="19" class="text-center py-8" style="color:var(--mt)"><i class="fa-solid fa-magnifying-glass text-lg mb-1 block"></i>'+(cls.length?'لا توجد نتائج':'لا توجد بيانات')+'</td></tr>';return}
tb.innerHTML=fl.map(function(c,i){var st=getSt(c),ph=esc(en(c.phone||c.mobile||'—')),cd=fmtDtS(c.createdAt),rd='';
if(st==='refunded'&&c.refundDate&&c.refundDate.seconds)rd='<span class="num" style="font-size:11px;color:#22c55e;font-weight:700">'+(ht?fmtDt(c.refundDate):fmtDtT(c.refundDate))+'</span>';else rd='<span style="color:var(--mt);font-size:12px">—</span>';
var ce=a||(st==='uploaded'&&pm.canEdit),pc,dc,cc,nc;
if(ce){pc='<input type="number" class="ism num" value="'+en(c.packagePrice||0)+'" step="0.01" dir="ltr" onchange="upF(\''+c.id+'\',\'packagePrice\',this.value)">';dc='<input type="number" class="ism num" value="'+en(c.packageDays||0)+'" dir="ltr" onchange="upF(\''+c.id+'\',\'packageDays\',this.value)">';cc='<input type="number" class="ism num" value="'+en(c.consumedDays||0)+'" dir="ltr" onchange="upF(\''+c.id+'\',\'consumedDays\',this.value)">';nc='<input type="text" class="ism w" value="'+escA(c.notes||'')+'" placeholder="—" onchange="upF(\''+c.id+'\',\'notes\',this.value)">'}
else{pc='<span class="ro num">'+en(c.packagePrice||0)+'</span>';dc='<span class="ro num">'+en(c.packageDays||0)+'</span>';cc='<span class="ro num">'+en(c.consumedDays||0)+'</span>';nc='<span class="ro" style="max-width:100px;display:inline-block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+escA(c.notes||'')+'">'+esc(c.notes||'—')+'</span>'}
var rc='';if(a&&st==='refunded')rc='<td><input type="text" class="ism rf" value="'+escA(c.referenceNumber||'')+'" placeholder="أدخل الرقم" dir="ltr" onchange="upRf(\''+c.id+'\',this.value)"></td>';else if(c.referenceNumber)rc='<td><span class="num" style="color:#f59e0b;font-weight:700;font-size:12px">'+esc(c.referenceNumber)+'</span></td>';else rc='<td><span style="color:var(--mt);font-size:12px">—</span></td>';
var ac='';if(a)ac='<button type="button" class="bd" onclick="dlC(\''+c.id+'\')"><i class="fa-solid fa-trash-can"></i></button>';else if(st==='uploaded'&&pm.canDelete)ac='<button type="button" class="bd" onclick="dlC(\''+c.id+'\')"><i class="fa-solid fa-trash-can"></i></button>';else ac='<span style="color:var(--mt);font-size:10px"><i class="fa-solid fa-lock"></i></span>';
// ✅ Only admin can click to approve/refund — users see a static badge
var stHtml;
if(a&&st==='pending'){stHtml='<td><button type="button" class="sb sb-click sb-p" onclick="apR(\''+c.id+'\')" title="اضغط للموافقة والتحويل إلى تم الاسترداد"><i class="'+STI[st]+' ml-0.5" style="font-size:9px"></i> '+STL[st]+'</button></td>'}else{stHtml='<td><span class="sb '+STC[st]+'"><i class="'+STI[st]+' ml-0.5" style="font-size:9px"></i> '+STL[st]+'</span></td>'}
return'<tr class="rn '+(c.previouslyRefunded?'pr':'')+'"><td class="font-bold text-[13px] num">'+(i+1)+'</td><td>'+esc(c.name)+(c.previouslyRefunded?' <span class="pb-t"><i class="fa-solid fa-triangle-exclamation"></i> سبق</span>':'')+'</td><td><span class="num" dir="ltr" style="font-size:12px">'+ph+'</span></td><td class="text-[11px] whitespace-nowrap" style="color:var(--dm)">'+esc(c.subscriptionDate||'—')+'</td><td class="text-[11px] whitespace-nowrap" style="color:var(--dm)">'+esc(c.packageType)+'</td><td class="num">'+pc+'</td><td class="num">'+dc+'</td><td class="num">'+cc+'</td><td class="rv num">'+en((c.refundAmount||0).toFixed(2))+'</td><td class="text-[11px] whitespace-nowrap" style="color:var(--dm)">'+esc(c.cancelDate||'—')+'</td><td class="text-[11px] whitespace-nowrap" style="color:var(--dm)">'+esc(c.cancellationPeriod||'—')+'</td><td class="text-[11px]" style="color:var(--dm);max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap" title="'+escA(c.cancelReason||'')+'">'+esc(c.cancelReason||'—')+'</td><td class="text-[11px] whitespace-nowrap" style="color:var(--mt)">'+cd+'</td><td>'+rd+'</td><td class="text-[11px]"><span style="color:rgba(0,212,170,.6)">'+esc(c.addedByUsername||'—')+'</span></td>'+stHtml+rc+'<td>'+nc+'</td><td>'+ac+'</td></tr>'}).join('')}
function upF(id,f,v){var u={};if(f==='packagePrice'||f==='packageDays'||f==='consumedDays'){u[f]=parseFloat(v)||0;var c=cls.find(function(x){return x.id===id});if(c)u.refundAmount=cRf(f==='packagePrice'?parseFloat(v)||0:c.packagePrice||0,f==='packageDays'?parseFloat(v)||0:c.packageDays||0,f==='consumedDays'?parseFloat(v)||0:c.consumedDays||0)}else u[f]=v;db.collection('cancellations').doc(id).update(u).catch(function(){toast('خطأ في التحديث','e')})}
function upRf(id,v){db.collection('cancellations').doc(id).update({referenceNumber:v}).then(function(){toast('تم تحديث الرقم المرجعي','s')}).catch(function(){toast('خطأ','e')})}
function dlC(id){sCf('هل أنت متأكد من حذف هذا العميل نهائياً؟',function(){db.collection('cancellations').doc(id).delete().then(function(){toast('تم الحذف بنجاح','s');chkP()}).catch(function(){toast('خطأ في الحذف','e')})})}
// ✅ FIX: Only admin can change status to pending
function toPn(id){if(!cu||cu.role!=='admin'){toast('للمدير فقط','e');return}db.collection('cancellations').doc(id).update({status:'pending',refunded:false}).then(function(){toast('تم التحويل إلى قيد المراجعة','s');ldPd();chkP()}).catch(function(){toast('خطأ','e')})}
// ✅ FIX: Only admin can approve refund
function apR(id){if(!cu||cu.role!=='admin'){toast('للمدير فقط','e');return}var c=cls.find(function(x){return x.id===id});db.collection('cancellations').doc(id).update({status:'refunded',refunded:true,refundDate:firebase.firestore.FieldValue.serverTimestamp(),previouslyRefunded:c?c.previouslyRefunded||false:false}).then(function(){toast('تمت الموافقة على الاسترداد','s');ldPd();chkP();rnT()}).catch(function(){toast('خطأ','e')})}
function chkPD(){var n=document.getElementById('fN').value.trim(),p=document.getElementById('fPh').value.trim();if(!n&&!p){document.getElementById('pW').classList.remove('on');return}var d=cls.find(function(c){if(n&&c.name===n)return true;if(p&&(c.phone===p||c.mobile===p))return true;return false});if(d){document.getElementById('pW').classList.add('on');document.getElementById('pWT').textContent='تحذير: العميل موجود مسبقاً ('+esc(d.name)+')'}else document.getElementById('pW').classList.remove('on')}
function uPv(){var p=parseFloat(document.getElementById('fPr').value)||0,d=parseFloat(document.getElementById('fDy').value)||0,c=parseFloat(document.getElementById('fCo').value)||0;document.getElementById('pRf').textContent=cRf(p,d,c).toFixed(2)}
// ✅ FIXED: Full template parsing — reads سبب الالغاء, عدد الايام المستهلكة, مدة الالغاء
// Consumed days now come from explicit template field, NOT from package name
function prsTm(){
    var t=document.getElementById('tmI').value;
    if(!t.trim())return;
    var n='',ph='',pk='',dt='',rs='',co='',dr='',sub='';
    t.split('\n').forEach(function(l){
        l=l.trim();if(!l)return;
        var idx=l.indexOf(':');if(idx<0)return;
        var k=l.substring(0,idx).trim(),v=l.substring(idx+1).trim();
        var kn=k.replace(/[أإآ]/g,'ا').replace(/ة/g,'ه');
        if(kn.includes('اسم')&&kn.includes('عميل')){n=v}
        else if(kn.includes('رقم')&&!kn.includes('مرجع')){ph=v}
        else if(kn.includes('مستهلك')){co=v}
        else if(kn.includes('سبب')&&!kn.includes('تعذر')&&!kn.includes('تسليم')){rs=v}
        else if(kn.includes('اشتراك')){sub=v}
        else if(kn.includes('تاريخ')){dt=v}
        else if(kn.includes('مده')){dr=v}
        else if(kn.includes('باقه')||kn.includes('نوع')){pk=v}
    });
    if(n)document.getElementById('fN').value=n;
    if(ph)document.getElementById('fPh').value=ph;
    if(pk)document.getElementById('fPk').value=pk;
    if(dt)document.getElementById('fDt').value=dt;
    if(rs)document.getElementById('fRs').value=rs;
    if(dr)document.getElementById('fDr').value=dr;
    if(sub)document.getElementById('fSub').value=sub;
    // Set consumed days from explicit template field if provided
    if(co){var cv=parseFloat(en(co));if(!isNaN(cv)&&cv>=0)document.getElementById('fCo').value=cv}
    // Extract price and total days from package type
    // Only fill consumed days from package name if NOT provided by template
    if(pk){
        var nums=pk.match(/[\d.]+/g);
        if(nums&&nums.length>=3){
            document.getElementById('fPr').value=nums[nums.length-3];
            if(!co)document.getElementById('fCo').value=nums[nums.length-2];
            document.getElementById('fDy').value=nums[nums.length-1];
        }else if(nums&&nums.length>=2){
            document.getElementById('fPr').value=nums[nums.length-2];
            document.getElementById('fDy').value=nums[nums.length-1];
        }else if(nums&&nums.length===1){document.getElementById('fPr').value=nums[0]}
    }
    uPv();chkPD();
}
// ✅ Save cancellationPeriod (مدة الإلغاء) to Firestore
function addC(){var n=document.getElementById('fN').value.trim(),ph=document.getElementById('fPh').value.trim(),pk=document.getElementById('fPk').value.trim(),dt=document.getElementById('fDt').value.trim(),dr=document.getElementById('fDr').value.trim(),sub=document.getElementById('fSub').value.trim(),pr=parseFloat(document.getElementById('fPr').value)||0,dy=parseFloat(document.getElementById('fDy').value)||0,co=parseFloat(document.getElementById('fCo').value)||0,rs=document.getElementById('fRs').value.trim(),no=document.getElementById('fNo').value.trim();
if(!n){toast('أدخل اسم العميل','e');return}if(!ph){toast('أدخل الرقم','e');return}if(!pk){toast('أدخل نوع الباقة','e');return}
db.collection('cancellations').add({name:n,phone:ph,mobile:ph,packageType:pk,cancelDate:dt,cancellationPeriod:dr,subscriptionDate:sub,packagePrice:pr,packageDays:dy,consumedDays:co,refundAmount:cRf(pr,dy,co),cancelReason:rs,notes:no,status:'uploaded',refunded:false,previouslyRefunded:false,addedByUsername:cu.username,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){toast('تم إضافة العميل','s');clCM()}).catch(function(e){toast('خطأ في الإضافة','e');console.error(e)})}
function togEm(){document.getElementById('exM').classList.toggle('on')}
// ✅ Export includes مدة الإلغاء and سبب الإلغاء columns
function gED(data){return data.map(function(c,i){return{'#':i+1,'اسم العميل':c.name,'الرقم':c.phone||c.mobile||'','تاريخ الاشتراك':c.subscriptionDate||'','نوع الباقة':c.packageType,'سعر الباقة':c.packagePrice||0,'أيام الباقة':c.packageDays||0,'أيام مستهلكة':c.consumedDays||0,'المبلغ المسترد':c.refundAmount||0,'تاريخ الإلغاء':c.cancelDate||'','مدة الإلغاء':c.cancellationPeriod||'','سبب الإلغاء':c.cancelReason||'','تاريخ الإضافة':c.createdAt?fmtDtT(c.createdAt):'','تاريخ الاسترداد':c.refundDate?fmtDtT(c.refundDate):'','أضاف بواسطة':c.addedByUsername||'','الحالة':STL[getSt(c)]||'','الرقم المرجعي':c.referenceNumber||'','ملاحظات':c.previouslyRefunded?'سبق الاسترداد':(c.notes||'')}})}
function dExp(data,fn){try{var wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('استرداد العملاء');
var hd=['#','اسم العميل','الرقم','تاريخ الاشتراك','نوع الباقة','سعر الباقة','أيام الباقة','أيام مستهلكة','المبلغ المسترد','تاريخ الإلغاء','مدة الإلغاء','سبب الإلغاء','تاريخ الإضافة','تاريخ الاسترداد','أضاف بواسطة','الحالة','الرقم المرجعي','ملاحظات'];
var cw=[5,22,16,16,22,14,12,12,16,14,14,20,18,18,18,14,14,16];
ws.columns=hd.map(function(h,i){return{header:'',key:h,width:cw[i]||15}});
ws.spliceRows(1,1);
var tr=ws.addRow(['نظام استرداد العملاء V-SHAPE','','','','','','','','','','','','','','','','','']);ws.mergeCells('A1:R1');tr.height=36;tr.getCell(1).value='نظام استرداد العملاء V-SHAPE';tr.getCell(1).font={name:'Tajawal',size:16,bold:true,color:{argb:'FFFFFFFF'}};tr.getCell(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0D9488'}};tr.getCell(1).alignment={horizontal:'center',vertical:'middle'};ws.getRow(1).height=36;
var sr2=ws.addRow([]);sr2.height=6;
var hr=ws.addRow(hd);hr.height=28;hr.eachCell(function(cell){cell.font={name:'Tajawal',size:11,bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F766E'}};cell.alignment={horizontal:'center',vertical:'middle',wrapText:true};cell.border={top:{style:'thin',color:{argb:'FF0D9488'}},bottom:{style:'thin',color:{argb:'FF0D9488'}},left:{style:'thin',color:{argb:'FF14B8A6'}},right:{style:'thin',color:{argb:'FF14B8A6'}}}});
data.forEach(function(c,idx){var row=ws.addRow(Object.values(c));row.height=24;var ip=c['ملاحظات']&&c['ملاحظات'].includes('سبق');row.eachCell(function(cell,col){cell.font={name:'Tajawal',size:11};cell.alignment={horizontal:'center',vertical:'middle',wrapText:true};cell.border={top:{style:'thin',color:{argb:'FFE2E8F0'}},bottom:{style:'thin',color:{argb:'FFE2E8F0'}},left:{style:'thin',color:{argb:'FFE2E8F0'}},right:{style:'thin',color:{argb:'FFE2E8F0'}}};if(ip){cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFEE2E2'}};cell.font={name:'Tajawal',size:11,color:{argb:'FF991B1B'}}}else if(idx%2===1)cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF8FAFC'}};if(col===8){cell.font={name:'Tajawal',size:11,bold:true,color:{argb:'FF0F766E'}};cell.numFmt='#,##0.00'}if(col===15){var st=c['الحالة'];if(st==='تم الاسترداد')cell.font={name:'Tajawal',size:11,bold:true,color:{argb:'FF16A34A'}};else if(st==='قيد المراجعة')cell.font={name:'Tajawal',size:11,bold:true,color:{argb:'FFE97A2A'}};else cell.font={name:'Tajawal',size:11,color:{argb:'FF64748B'}}}if(col===16&&c['الرقم المرجعي'])cell.font={name:'Tajawal',size:11,bold:true,color:{argb:'FFB45309'}}})});
wb.xlsx.writeBuffer().then(function(buf){var bl=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});var u=URL.createObjectURL(bl);var a=document.createElement('a');a.href=u;a.download=fn+'.xlsx';a.click();URL.revokeObjectURL(u);toast('تم التصدير بنجاح','s')}).catch(function(e){console.error(e);toast('خطأ في التصدير: '+e.message,'e')})} catch(e){console.error('Export error:',e);toast('خطأ في التصدير','e')}}
function expD(){var n=new Date(),td=n.getFullYear()+'-'+String(n.getMonth()+1).padStart(2,'0')+'-'+String(n.getDate()).padStart(2,'0');var d=gED(cls.filter(function(c){if(!c.createdAt||!c.createdAt.seconds)return false;var x=new Date(c.createdAt.seconds*1000);return x.getFullYear()===n.getFullYear()&&x.getMonth()===n.getMonth()&&x.getDate()===n.getDate()}));if(!d.length){toast('لا توجد بيانات اليوم','w');return}dExp(d,'استرداد_'+td)}
function expByDt(){var dv=document.getElementById('exDt').value;if(!dv){toast('اختر تاريخ','e');return}var d=gED(cls.filter(function(c){if(!c.createdAt||!c.createdAt.seconds)return false;var x=new Date(c.createdAt.seconds*1000),p=dv.split('-');return x.getFullYear()===parseInt(p[0])&&x.getMonth()===parseInt(p[1])-1&&x.getDate()===parseInt(p[2])}));if(!d.length){toast('لا توجد بيانات','w');return}dExp(d,'استرداد_'+dv)}
function expA(){if(!cls.length){toast('لا توجد بيانات','w');return}dExp(gED(cls),'استرداد_الكل')}
document.addEventListener('click',function(e){if(!e.target.closest('#exM')&&!e.target.closest('#exB'))document.getElementById('exM').classList.remove('on')});
document.addEventListener('keydown',function(e){if(e.key==='Escape'){clCM();clAP();cfNo()}});
window.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.tb i').forEach(function(i){i.className=isDk?'fa-solid fa-sun':'fa-solid fa-moon'});initDF();try{if(!firebase.apps.length)firebase.initializeApp(FC);db=firebase.firestore();db.collection('users').limit(1).get().then(function(snap){document.getElementById('connErr').style.display='none';document.getElementById('fh').style.display=snap.empty?'block':'none';var sv=sessionStorage.getItem('cu');if(sv){try{cu=JSON.parse(sv);shApp();stL();chkP()}catch(e){sessionStorage.removeItem('cu')}}}).catch(function(e){console.error(e);document.getElementById('connErr').style.display='flex'})}catch(e){console.error('Init error:',e);document.getElementById('connErr').style.display='flex'}});
